site_name: Nahom Portfolio
# site_url: https://nahomsososa.com/portfolio
site_author: Nahom Sososa
site_description: Nahom's data and gaming portfolio

theme:
  name: "material"
  palette:
    primary: "purple"
    accent: "white"
  features:
    - navigation.footer
  #font:
    #text:
  #logo:
plugins:
    - search
   
nav:
  - Home: index.md
  - About: about.md

markdown_extensions: # for syntax highlighting in code blocks
  - pymdownx.superfences:
  - pymdownx.highlight:
      use_pygments: true

extra_css:
- 'stylesheets/extra.css'
#- 'https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap'

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/nahomsososa/
      name: Nahom on LinkedIn
